Repository NVIDIA-Merlin/core, pull requests merged in 2022-09, with the labels that each got.

#127 Split the downstream repo tests into separate Tox environments and Github actions
  .github/workflows/cpu-ci.yml
  .github/workflows/cpu-models.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  tox.ini
Labels: ci, chore

#124 Improve the organization of the schema tests (column vs schema vs io)
  tests/unit/schema/test_column_schemas.py
  tests/unit/schema/test_schema.py
  tests/unit/schema/test_schema_io.py
Labels: clean up, chore

#125 Migrate Merlin DAG executors from NVTabular
  merlin/dag/executors.py
Labels: clean up, chore

#130 ensure that combinations of nodes can be used as subgraphs
  merlin/dag/graph.py
  tests/unit/dag/test_graph.py
Labels: bug

#129 Expand `models` testing in PR checks to include TF and other frameworks
  tox.ini
Labels: ci, chore

#136 Combine changes that address downstream failures
  tox.ini
Labels: ci, chore

#132 Fix versioneer to get accurate version numbers
  merlin/core/_version.py
  setup.cfg
  tests/unit/core/test_version.py
Labels: ci

#137 Switch downstream repo tests from `build` to `check` (to make optional)
  .github/workflows/cpu-models.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
Labels: ci, chore

#140 Break `LocalExecutor.transform()` down into smaller methods
  merlin/dag/executors.py
Labels: clean up, chore
