Repository NVIDIA-Merlin/core, pull requests merged in 2022-10, with the labels that each got.

#143 Add wildcard selector for cases where you'd like to select all columns
  merlin/dag/selector.py
  merlin/schema/schema.py
  tests/unit/dag/test_column_selector.py
  tests/unit/schema/test_schema.py
Labels: enhancement

#145 Avoid using numba to set device context in import
  merlin/core/compat.py
Labels: bug

#147 Fix ambigous statement when names is a list
  merlin/dag/selector.py
Labels: bug

#151 Specify minimum Python version as 3.8 in `setup.py`
  setup.py
Labels: chore

#76 Add a `validate_schemas` hook to clean up downstream validation code
  merlin/dag/base_operator.py
  merlin/dag/node.py
Labels: clean up, chore

#146 Resolve wildcard selectors in `BaseOperator.compute_selector()`
  merlin/dag/base_operator.py
  merlin/dag/ops/concat_columns.py
  merlin/dag/ops/subtraction.py
Labels: bug

#131 Add XGBoost to `merlin-models` CPU tests
  tox.ini
Labels: ci, chore

#154 Fix dtype inference from pandas list column
  merlin/core/dispatch.py
  tests/unit/core/test_dispatch.py
Labels: bug

#153 Patch `is_list_dtype`/`list_val_dtype` to work with Numpy ndarrays
  merlin/core/dispatch.py
Labels: bug

#155 Serialize/Deserialize `ColumnSchema` consistently when the domain name matches the feature name
  merlin/schema/io/tensorflow_metadata.py
  tests/unit/schema/test_schema_io.py
Labels: chore

#157 Update `with_properties` to enable changing existing properties on `ColumnSchema`
  merlin/schema/schema.py
  tests/unit/schema/test_column_schemas.py
Labels: bug, chore
