Repository NVIDIA-Merlin/core, pull requests merged in 2022-08, with the labels that each got.

#112 Set `HAS_GPU = False` in `dispatch` if relevant packages fail to import
  merlin/core/dispatch.py
Labels: bug

#113 Pin `fsspec==2022.5.0`
  requirements.txt
Labels: ci, chore

#114 Update `versioneer` from 0.21 to 0.23
  merlin/core/__init__.py
  merlin/core/_version.py
  versioneer.py
Labels: chore

#117 Auto-update pre-commit hook packages
  .pre-commit-config.yaml
Labels: clean up, chore

#118 Add a `quantity` attribute to `ColumnSchema`
  merlin/schema/schema.py
  tests/unit/schema/test_schema.py
Labels: enhancement, clean up

#119 Split compound tags (like `USER_ID`) into atomic tags (like `USER`,`ID`)
  merlin/schema/tags.py
  tests/unit/schema/test_tags.py
Labels: enhancement, clean up, chore

#116 Use mambabuild for generating conda package in github actions
  .github/workflows/cpu-ci.yml
Labels: ci

#122 fix pull apart list for newer cudf versions
  merlin/core/dispatch.py
Labels: ci, chore, breaking

#126 Migrate test environment to `tox`
  .github/workflows/cpu-ci.yml
  .github/workflows/docs-sched-rebuild.yaml
  requirements-dev.txt
  requirements-docs.txt
  requirements-gpu.txt
  requirements-test-cpu.txt
  requirements-test-gpu.txt
  requirements-test.txt
  requirements.txt
  tox.ini
Labels: ci, chore
