Repository NVIDIA-Merlin/core, pull requests merged in 2022-03, with the labels that each got.

#29 Fix node selectors
  merlin/dag/node.py
Labels: bug

#28 Versioneer fixes
  MANIFEST.in
  setup.py
Labels: bug

#34 Set up automated docstring coverage checks
  .github/workflows/cpu-ci.yml
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: documentation

#33 Make `BaseOperator.dependencies` a property
  merlin/dag/base_operator.py
  merlin/dag/node.py
Labels: bug

#35 Add docstrings to `merlin.schema`
  .github/workflows/cpu-ci.yml
  .pre-commit-config.yaml
  merlin/io/dataset.py
  merlin/io/parquet.py
  merlin/schema/io/proto_utils.py
  merlin/schema/io/tensorflow_metadata.py
  merlin/schema/schema.py
  merlin/schema/tags.py
Labels: documentation

#45 Move interrogate docstring coverage settings to pyproject.toml
  .github/workflows/cpu-ci.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: documentation

#49 Exclude additional directories from docstring coverage checks
  pyproject.toml
Labels: documentation

#50 Additional docstrings from bash
  docs/source/api/index.rst
  docs/source/api/merlin.dag.rst
  merlin/dag/node.py
  merlin/dag/ops/__init__.py
  merlin/dag/ops/concat_columns.py
  merlin/dag/ops/identity.py
  merlin/dag/ops/selection.py
  merlin/dag/ops/subset_columns.py
  merlin/dag/ops/subtraction.py
  pyproject.toml
  requirements-dev.txt
Labels: documentation

#52 Move `merlin.core.worker` to `merlin.io.worker`
  merlin/io/dask.py
  merlin/io/worker.py
  requirements-dev.txt
Labels: clean up
