Repository NVIDIA-Merlin/core, pull requests merged in 2022-11, with the labels that each got.

#152 necessary changes to allow graph execution in dataloader
  merlin/dag/executors.py
  merlin/dag/ops/selection.py
  tests/unit/dag/ops/test_selection.py
Labels: enhancement

#158 Rework executor `transform` methods to accept a `Graph`
  merlin/dag/executors.py
Labels: clean up, chore

#160 docs: Add basic SEO configuration
  docs/source/conf.py
Labels: documentation

#163 Remove explicit `DictArray` reference from `merlin.core.dispatch`
  merlin/core/dispatch.py
  merlin/dag/dictarray.py
Labels: clean up, chore

#165 Fix `concat_columns` for DataFrames with list features
  merlin/core/dispatch.py
  tests/unit/core/test_dispatch.py
Labels: chore

#166 Remove the `@property` annotation from `Transformable.columns`
  merlin/core/protocols.py
  merlin/dag/dictarray.py
Labels: bug

#159 Fix file-count warning in Dataset.to_parquet
  merlin/io/dataset.py
Labels: bug

#161 docs: Add temp semver to calver banner
  docs/source/_static/css/custom.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#169 Fix feature.shape attribute in from_merlin_schema
  merlin/schema/io/tensorflow_metadata.py
Labels: bug

#111 Update `value_count` serialization/deserialization to be consistent with original schema
  merlin/schema/io/tensorflow_metadata.py
  merlin/schema/schema.py
  tests/unit/schema/test_column_schemas.py
  tests/unit/schema/test_schema_io.py
Labels: bug

#171 Enable partial value count to be specified
  merlin/schema/schema.py
  tests/unit/schema/test_column_schemas.py
Labels: enhancement

#172 Change `is_ragged` property based on value_count in with_properties
  merlin/schema/schema.py
  tests/unit/schema/test_column_schemas.py
Labels: enhancement

#167 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: ci, chore, gpuCI-test-this

#173 Remove specifying `is_ragged` in LocalExecutor `_transform_data`
  merlin/dag/executors.py
Labels: chore

#174 update drafter to work on tags & update cpu ci to target branches
  .github/workflows/cpu-ci.yml
  .github/workflows/cpu-models.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/release-drafter.yaml
  tox.ini
Labels: ci, chore
