Repository NVIDIA-Merlin/core, pull requests merged in 2022-12, with the labels that each got.

#178 Read parquet statistics to optimize len when they are missing
  merlin/io/dataset.py
  merlin/io/parquet.py
  tests/unit/io/test_io.py
Labels: enhancement

#180 add is_list detection for merlin columns
  merlin/core/dispatch.py
Labels: enhancement

#185 Update Models/NVTabular test config
  tox.ini
Labels: ci

#184 Use pre-commit for linting in GitHub Actions Workflow
  .github/workflows/cpu-ci.yml
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  .pylintrc
  merlin/core/dispatch.py
  merlin/core/utils.py
  merlin/dag/base_operator.py
  merlin/dag/node.py
  merlin/dag/selector.py
  merlin/io/avro.py
  merlin/io/dask.py
  merlin/io/hugectr.py
  merlin/io/parquet.py
  merlin/io/worker.py
  merlin/schema/schema.py
  merlin/schema/tags.py
  mypy.ini
  requirements-dev.txt
  tox.ini
  versioneer.py
Labels: ci

#191 adding workflow for GPU CI on gha
  .github/workflows/gpu-ci.yml
Labels: clean up, ci, chore

#192 Add the schema to the output of the `.repartition()` method
  merlin/io/dataset.py
Labels: bug, P0

#193 skip notebook tests in models test
  tox.ini
Labels: ci, chore
