Repository NVIDIA-Merlin/core, pull requests merged in 2022-05, with the labels that each got.

#79 docs: Add ext-toc and copydirs
  docs/source/conf.py
  docs/source/index.rst
  docs/source/toc.yaml
  requirements-dev.txt
Labels: documentation

#78 Change `dask` and `distributed` deps to `==2021.11.2`
  requirements.txt
Labels: clean up

#84 arrow downgrade in requirements
  requirements.txt
Labels: bug

#87 Add conda builds to our github actions workflow
  .github/workflows/cpu-ci.yml
Labels: ci

#90 Request adding labels to PRs
  CONTRIBUTING.md
Labels: chore
