Repository NVIDIA-Merlin/core, pull requests merged in 2022-04, with the labels that each got.

#53 README updates
  .gitignore
  README.md
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#58 Generalize the fix for Pandas extension dtypes
  merlin/schema/schema.py
Labels: clean up

#56 Exclude `merlin/io` from docstring coverage checks
  .pre-commit-config.yaml
  pyproject.toml
Labels: documentation

#60 Avoid nullable pandas dtypes in CPUParquetEngine
  merlin/io/parquet.py
Labels: bug

#65 Remove use of `kind` property in `ColumnSchema`
  merlin/schema/schema.py
Labels: bug

#64 docs: Add redirect page
  .github/workflows/docs-sched-rebuild.yaml
Labels: documentation

#71 Standardize our pre-commit hooks
  .pre-commit-config.yaml
  merlin/core/__init__.py
  merlin/dag/__init__.py
  merlin/dag/ops/__init__.py
  merlin/io/__init__.py
  merlin/io/avro.py
  merlin/io/csv.py
  merlin/io/dask.py
  merlin/io/dataframe_engine.py
  merlin/io/dataset.py
  merlin/io/hugectr.py
  merlin/io/parquet.py
  merlin/io/writer.py
  merlin/io/writer_factory.py
  merlin/schema/__init__.py
  merlin/schema/io/tensorflow_metadata.py
  merlin/schema/schema.py
Labels: clean up

#72 Add mypy to the commit hooks and address typing issues
  .pre-commit-config.yaml
  merlin/core/dispatch.py
  merlin/io/csv.py
  merlin/io/parquet.py
  merlin/io/writer.py
  merlin/schema/io/tensorflow_metadata.py
  merlin/schema/schema.py
  merlin/schema/tags.py
Labels: clean up

#73 Add Github issue templates
  .github/workflows/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/ISSUE_TEMPLATE/documentation-request.md
  .github/workflows/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/ISSUE_TEMPLATE/submit-question.md
  .github/workflows/ISSUE_TEMPLATE/task.md
Labels: clean up

#77 update distributed and dask to new version
  requirements.txt
Labels: bug
