Repository NVIDIA-Merlin/core, pull requests merged in 2023-07, with the labels that each got.

#354 add check for respective packages in dataformat
  merlin/dag/executors.py
Labels: bug

#356 Unify API Structure
  docs/source/api/merlin.dag.rst
  docs/source/api/merlin.io.rst
  docs/source/api/merlin.schema.rst
  docs/source/conf.py
Labels: documentation

#358 move base runtime to core
  merlin/dag/base_runtime.py
Labels: enhancement

#359 migrate base operator to operator and base_runtime to runtime
  docs/source/api/merlin.dag.rst
  merlin/dag/__init__.py
  merlin/dag/graph.py
  merlin/dag/node.py
  merlin/dag/operator.py
  merlin/dag/ops/add_metadata.py
  merlin/dag/ops/concat_columns.py
  merlin/dag/ops/rename.py
  merlin/dag/ops/selection.py
  merlin/dag/ops/stat_operator.py
  merlin/dag/ops/subset_columns.py
  merlin/dag/ops/subtraction.py
  merlin/dag/ops/udf.py
  merlin/dag/runtime.py
  merlin/dag/selector.py
  tests/unit/dag/ops/test_subgraph.py
  tests/unit/dag/test_base_operator.py
  tests/unit/dag/test_column_selector.py
  tests/unit/dag/test_executors.py
  tests/unit/dag/test_graph.py
  tests/unit/table/test_tensor_table.py
Labels: enhancement, clean up, api
