Repository NVIDIA-Merlin/core, pull requests merged in 2023-06, with the labels that each got.

#341 Correct dask cluster type check
  merlin/io/dataset.py
  tests/unit/io/test_dataset.py
Labels: bug, skip-changelog

#340 Always build docs from main branch in docs-sched-rebuild
  .github/workflows/docs-sched-rebuild.yaml
  merlin/io/dataset.py
Labels: documentation

#334 Add `Subgraph` op to define & reuse parts of larger graphs
  merlin/dag/base_operator.py
  merlin/dag/executors.py
  merlin/dag/graph.py
  merlin/dag/node.py
  merlin/dag/ops/concat_columns.py
  merlin/dag/ops/subgraph.py
  tests/unit/dag/ops/test_subgraph.py
  tests/unit/dag/test_graph.py
Labels: enhancement, breaking

#342 Fix udf op
  merlin/dag/ops/udf.py
  tests/unit/dag/ops/test_udf.py
Labels: bug

#343 changes required to make subgraphs work in nvt
  merlin/dag/executors.py
  merlin/dag/graph.py
  merlin/dag/node.py
  merlin/dag/ops/subgraph.py
Labels: enhancement

#344 migrate metadata operators to core
  merlin/dag/ops/__init__.py
  merlin/dag/ops/add_metadata.py
  tests/unit/dag/ops/test_addmetadata.py
Labels: chore

#349 add changes to support subgraph in multistage example
  merlin/dag/base_operator.py
  merlin/dag/graph.py
  merlin/dag/ops/subgraph.py
Labels: enhancement, clean up, api

#350 Make output of transform same type as input
  merlin/dag/executors.py
Labels: bug, clean up, chore

#353 fix the column merging during graph traversal and concat selector
  merlin/dag/executors.py
  merlin/dag/node.py
  merlin/dag/ops/__init__.py
  merlin/dag/ops/concat_columns.py
  merlin/dag/ops/grouping.py
  tests/unit/dag/test_graph.py
Labels: bug
