Repository NVIDIA-Merlin/core, pull requests merged in 2023-02, with the labels that each got.

#207 Add note on why we're using `device_get_count` instead of `cuda.gpus`
  merlin/core/compat.py
Labels: chore

#209 Install latest version of NVTabular/dataloader with systems tests
  tox.ini
Labels: chore

#208 Update pre-commit config with latest versions of repos
  .pre-commit-config.yaml
  merlin/dtypes/__init__.py
  merlin/io/avro.py
  merlin/io/csv.py
  merlin/io/dask.py
  merlin/io/dataset.py
  merlin/io/fsspec_utils.py
  merlin/io/parquet.py
  merlin/io/writer.py
  tests/unit/io/test_io.py
  tests/unit/utils/test_utils.py
Labels: chore

#210 Increase upper bound of `pandas` version from 1.4 to 1.6
  requirements.txt
Labels: chore

#195 Add a new `shape` field to `ColumnSchema`
  merlin/core/dispatch.py
  merlin/dag/executors.py
  merlin/dtypes/base.py
  merlin/dtypes/shape.py
  merlin/schema/io/tensorflow_metadata.py
  merlin/schema/schema.py
  tests/unit/dtypes/test_shape.py
  tests/unit/schema/test_column_schemas.py
  tests/unit/schema/test_schema.py
Labels: clean up, chore, breaking

#181 add gcp label to jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: ci, chore, gpuCI-test-this

#204 Fix for updated versions of cudf to parquet
  tests/conftest.py
Labels: enhancement, chore

#213 Support partially specified value_count when used with `is_ragged=False`
  merlin/schema/schema.py
  tests/unit/schema/test_column_schemas.py
Labels: enhancement

#214 Serialize shapes to and from Merlin schema files
  merlin/dtypes/shape.py
  merlin/schema/io/tensorflow_metadata.py
  tests/unit/schema/test_schema_io.py
Labels: chore

#182 Save schema with consistent dtype when `dtypes` is used
  merlin/io/dataset.py
  tests/unit/io/test_io.py
Labels: bug

#211 separate cupy import from rapids
  merlin/core/dispatch.py
Labels: enhancement, clean up

#217 Fill in some missing docstrings
  merlin/dag/graph.py
  merlin/dtypes/mapping.py
  merlin/dtypes/mappings/cudf.py
Labels: chore

#216 Add util functions for un/grouping column values/offsets in dicts
  merlin/dag/__init__.py
  merlin/dag/utils.py
  tests/unit/dag/test_dag_utils.py
Labels: clean up, chore

#205 Clean up of make_df function
  merlin/core/dispatch.py
  tests/unit/core/test_dispatch.py
Labels: enhancement, clean up, chore

#219 Reduce the overhead of using `LocalExecutor` (esp. dtype validation)
  merlin/dag/executors.py
  merlin/dtypes/base.py
  merlin/dtypes/mapping.py
Labels: clean up, chore

#215 Remove use of `is_list`/`is_ragged` and replace with setting shapes
  merlin/dag/base_operator.py
  merlin/dag/executors.py
  merlin/dtypes/shape.py
  merlin/io/dataset.py
  merlin/schema/schema.py
  tests/unit/schema/test_column_schemas.py
Labels: clean up, chore, breaking

#221 Update HAS_GPU variable to account for `CUDA_VISIBLE_DEVICES`
  merlin/core/compat.py
Labels: enhancement

#223 docs: Rebuild on push to the default branch
  .github/workflows/docs-sched-rebuild.yaml
Labels: chore, skip-changelog

#226 Handle executor transform case when parent node provides no new columns
  merlin/dag/executors.py
Labels: bug

#227 skip version test
  tests/unit/core/test_version.py
Labels: bug, ci, chore

#228 Skip version test
  tests/unit/core/test_version.py
Labels: bug, clean up, ci, chore

#222 Create a lazy dispatch mechanism based on `functools.singledispatch`
  merlin/dispatch/lazy.py
  tests/unit/dispatch/test_lazy_dispatch.py
Labels: enhancement
