Repository NVIDIA-Merlin/core, pull requests merged in 2023-01, with the labels that each got.

#198 Change the name of the package building action
  .github/workflows/cpu-packages.yml
Labels: ci, chore

#170 Create standard Merlin dtypes in the `merlin.dtypes` module
  merlin/dag/dictarray.py
  merlin/dag/executors.py
  merlin/dtypes/__init__.py
  merlin/dtypes/aliases.py
  merlin/dtypes/base.py
  merlin/dtypes/mapping.py
  merlin/dtypes/mappings/__init__.py
  merlin/dtypes/mappings/cudf.py
  merlin/dtypes/mappings/numpy.py
  merlin/dtypes/mappings/pandas.py
  merlin/dtypes/mappings/python.py
  merlin/dtypes/mappings/tf.py
  merlin/dtypes/mappings/torch.py
  merlin/dtypes/mappings/triton.py
  merlin/dtypes/registry.py
  merlin/schema/io/tensorflow_metadata.py
  merlin/schema/schema.py
  tests/unit/dtypes/test_module.py
  tests/unit/schema/test_column_schemas.py
  tests/unit/schema/test_schema_io.py
Labels: enhancement

#199 Add Formatter (Prettier) for YAML and Markdown files
  .github/release-drafter.yml
  .github/workflows/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/ISSUE_TEMPLATE/documentation-request.md
  .github/workflows/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/ISSUE_TEMPLATE/submit-question.md
  .github/workflows/ISSUE_TEMPLATE/task.md
  .github/workflows/cpu-ci.yml
  .github/workflows/cpu-models.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-packages.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/release-drafter.yaml
  .pre-commit-config.yaml
  .prettierignore
  CLA.md
  CONTRIBUTING.md
  README.md
  docs/README.md
Labels: clean up, ci, chore

#200 Update docs support info in README
  docs/README.md
Labels: chore, skip-changelog
