Repository NVIDIA-Merlin/core, pull requests merged in 2023-04, with the labels that each got.

#270 compat imports update
  merlin/core/compat.py
Labels: clean up, ci, chore

#271 change cpu conversion for tf to convert-to-tensor
  merlin/table/tensorflow_column.py
Labels: bug, chore

#272 migrate compat into a separate folder and separate tf and torch import
  merlin/core/compat/__init__.py
  merlin/core/compat/tensorflow.py
  merlin/core/compat/torch.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
  tests/unit/table/test_convert_column.py
  tests/unit/table/test_tensor_column.py
  tests/unit/table/test_tensor_table.py
Labels: chore, api

#274 fix cuda import logic from numba and device memsize
  merlin/core/compat/__init__.py
Labels: bug, chore

#275 update numpy version to handle dlpack
  requirements.txt
Labels: bug, clean up, ci, chore

#276 add hack to handle tf not recognizing bool dtype in dlpack
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  requirements-gpu.txt
  tox.ini
Labels: bug

#278 Extend mapping of nullable types for pandas
  merlin/core/dispatch.py
  tests/unit/core/test_dispatch.py
Labels: enhancement

#281 Preserve type of shape dims as ints when re-loading schema from disk
  merlin/dtypes/shape.py
  merlin/schema/io/tensorflow_metadata.py
  tests/unit/schema/test_schema_io.py
Labels: chore

#279 Refactor `LocalExecutor` into more discrete steps that can be overridden
  merlin/dag/executors.py
  merlin/dag/node.py
Labels: clean up, chore

#283 Add `column_type` property to `TensorTable`
  merlin/table/tensor_table.py
  tests/unit/table/test_tensor_table.py
Labels: enhancement

#267 Save schema in old location for backwards compatibility
  merlin/io/dataset.py
  tests/unit/io/test_io.py
Labels: chore

#289 Install protobuf version compatible with tensorflow 2.9 for Merlin Models tests
  tox.ini
Labels: ci

#291 Update `pull_apart_list` to use `pd.concat` instead of deprecated `Series.append`
  merlin/core/dispatch.py
Labels: chore

#292 Various fixes for dataloader embedding op usage
  merlin/io/dataset.py
  merlin/schema/schema.py
Labels: bug

#294 change dependent workflow for documentation preview
  .github/workflows/docs-preview-pr.yaml
Labels: ci, chore

#295 CI: add quotes to workflow name
  .github/workflows/docs-preview-pr.yaml
Labels: chore
