Repository NVIDIA-Merlin/core, pull requests merged in 2023-03, with the labels that each got.

#230 Introduce TensorTable, a cross framework abstraction
  merlin/core/compat.py
  merlin/core/dispatch.py
  merlin/dispatch/lazy.py
  merlin/table/__init__.py
  merlin/table/conversions.py
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  merlin/table/tensor_column.py
  merlin/table/tensor_table.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
  tests/unit/dispatch/test_lazy_dispatch.py
  tests/unit/table/test_convert_column.py
  tests/unit/table/test_tensor_column.py
  tests/unit/table/test_tensor_table.py
  tox.ini
Labels: enhancement, chore

#232 Add `cpu()` and `gpu()` transfer methods to `TensorColumn/Table`
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  merlin/table/tensor_column.py
  merlin/table/tensor_table.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
  tests/unit/table/test_tensor_column.py
  tests/unit/table/test_tensor_table.py
Labels: enhancement

#231 Add shapes to `TensorColumn`s
  merlin/table/tensor_column.py
  tests/unit/table/test_tensor_column.py
Labels: enhancement

#233 Add `TensorTable.to/from_df()` methods
  merlin/core/dispatch.py
  merlin/table/__init__.py
  merlin/table/conversions.py
  merlin/table/tensor_table.py
  tests/unit/table/test_tensor_table.py
Labels: enhancement

#235 Small fixes surfaced while integrating `TensorTable`
  merlin/dag/node.py
  merlin/dtypes/shape.py
  merlin/schema/io/tensorflow_metadata.py
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
  tests/unit/table/test_tensor_column.py
  tests/unit/table/test_tensor_table.py
Labels: clean up, chore

#237 Add pynvml dependency
  requirements.txt
Labels: chore

#239 Add tag to describe column containing embeddings
  merlin/schema/tags.py
Labels: enhancement

#240 Add Schema `copy` method
  merlin/io/dataset.py
  merlin/schema/schema.py
Labels: enhancement

#241 Add correct job dependency for release in `cpu-packages`
  .github/workflows/cpu-packages.yml
Labels: ci

#242 Enable Schema selection using `select_by_tag` with string representation of `Tags` enum.
  merlin/schema/schema.py
  tests/unit/schema/test_schema.py
Labels: enhancement

#229 add import pytest to file
  tests/unit/core/test_version.py
Labels: bug, ci, chore

#249 Change the location and filename of schema.pbtxt to .merlin/schema.json
  merlin/io/__init__.py
  merlin/io/dataset.py
  merlin/schema/io/tensorflow_metadata.py
  tests/unit/io/test_io.py
Labels: chore

#244 Remove use of HAS_GPU from `dispatch` functions
  merlin/core/compat.py
  merlin/core/dispatch.py
Labels: chore

#250 Update `is_list_dtype` to handle additional types
  merlin/core/dispatch.py
Labels: chore

#251 Support cupy and numpy array types in `flatten_list_column_values`
  merlin/core/dispatch.py
Labels: chore

#253 Improve check for array types in `is_list_dtype`
  merlin/core/dispatch.py
Labels: chore

#94 Add predicate function argument to `select_by_tag`
  merlin/dag/selector.py
  merlin/schema/schema.py
  tests/unit/schema/test_schema.py
Labels: enhancement

#252 Allow casting a `Dimension` to an integer when min and max are the same
  merlin/dtypes/shape.py
Labels: enhancement

#247 Move common steps to run tox env into reusable workflow
  .github/workflows/cpu-ci.yml
  .github/workflows/cpu-dataloader.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/merlin.yml
  .github/workflows/tox.yml
Labels: ci

#236 Support `Dataset` cpu-mode in environment with GPUs that have not been detected
  .github/workflows/gpu-ci.yml
  merlin/core/dispatch.py
  merlin/io/dataset.py
  tests/conftest.py
  tests/unit/core/test_dispatch.py
  tests/unit/core/test_protocols.py
  tests/unit/io/test_io.py
  tests/unit/table/test_convert_column.py
  tests/unit/table/test_tensor_column.py
  tests/unit/table/test_tensor_table.py
  tests/unit/utils/test_utils.py
  tox.ini
Labels: enhancement

#243 Check environment supports target device in Dataset constructor
  merlin/io/dataset.py
  tests/conftest.py
  tests/unit/io/test_dataset.py
Labels: enhancement

#254 Preserve original Dask partitions by default in `Dataset.to_parquet`
  merlin/io/dask.py
  merlin/io/dataset.py
  tests/unit/io/test_io.py
Labels: breaking

#257 Make `TensorColumn` shape and dtype properties lazy but memoized
  merlin/dtypes/__init__.py
  merlin/table/tensor_column.py
Labels: clean up, chore

#258 Add an `unsafe` mode to `TensorTable`/`TensorColumn` (for internal use)
  merlin/table/tensor_column.py
  merlin/table/tensor_table.py
Labels: chore, api

#260 Propagate the `_unsafe` mode flag from `TensorTable` to `TensorColumn`
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  merlin/table/tensor_column.py
  merlin/table/tensor_table.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
Labels: bug

#262 Update `merlin.core.compat` to use `HAS_GPU` and add add'l libraries
  merlin/core/compat.py
Labels: clean up, chore

#261 Run with import without gpu
  merlin/core/utils.py
  merlin/dtypes/mappings/cudf.py
  merlin/io/avro.py
  merlin/io/csv.py
  merlin/io/dataframe_engine.py
  merlin/io/dataset.py
  merlin/io/fsspec_utils.py
  merlin/io/parquet.py
  merlin/io/shuffle.py
  merlin/io/worker.py
  merlin/io/writer.py
  merlin/table/conversions.py
  tests/conftest.py
  tests/unit/io/test_avro.py
  tests/unit/io/test_io.py
Labels: enhancement, chore

#263 Revert #261 and #262 (`merlin.core.compat` changes)
  merlin/core/compat.py
  merlin/core/utils.py
  merlin/dtypes/mappings/cudf.py
  merlin/io/avro.py
  merlin/io/csv.py
  merlin/io/dataframe_engine.py
  merlin/io/dataset.py
  merlin/io/fsspec_utils.py
  merlin/io/parquet.py
  merlin/io/shuffle.py
  merlin/io/worker.py
  merlin/io/writer.py
  merlin/table/conversions.py
  tests/conftest.py
  tests/unit/io/test_avro.py
  tests/unit/io/test_io.py
Labels: clean up, chore

#246 add 3d tensor support to creating tensor columns
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  merlin/table/tensor_column.py
  merlin/table/tensor_table.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
  tests/unit/table/test_convert_column.py
  tests/unit/table/test_tensor_column.py
Labels: enhancement, chore

#264 Propagate `_unsafe` flag through column constructors properly
  merlin/table/conversions.py
  merlin/table/cupy_column.py
  merlin/table/numpy_column.py
  merlin/table/tensor_table.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
Labels: bug

#265 migrate configure tensorflow to core, separate has_gpu from compat
  merlin/core/compat.py
  merlin/core/has_gpu.py
  merlin/core/utils.py
  merlin/io/dataset.py
Labels: ci, chore

#266 fix configure tf function to id all gpus available
  merlin/core/compat.py
Labels: ci, chore

#268 Disable strict dtype checking by default
  merlin/dag/executors.py
Labels: bug

#269 fix gpu numpy conversion offsets
  merlin/table/numpy_column.py
Labels: bug, chore
