Repository NVIDIA-Merlin/core, pull requests merged in 2023-05, with the labels that each got.

#299 Adjust the `DaskExecutor` API methods to take `Dataset`s instead of ddfs
  merlin/dag/executors.py
Labels: clean up, chore, breaking

#303 Add Workflow to update the stable branch ref to the latest tag
  .github/workflows/stable-branch.yaml
Labels: ci

#302 Move build-docs to separate job in packages workflow with Python 3.9
  .github/workflows/cpu-packages.yml
Labels: ci

#300 Update packages workflow, separating PyPI from conda build
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/packages.yaml
Labels: ci

#306 Revert "Adjust the `DaskExecutor` API methods to take `Dataset`s inst…
  merlin/dag/executors.py
Labels: clean up, chore

#307 don't re-run tests on closed PR
  .github/workflows/gpu-ci.yml
Labels: ci

#308 Remove use of deprecated numpy aliases of builtin types
  merlin/dtypes/mappings/numpy.py
  tests/unit/schema/test_schema_io.py
Labels: chore

#305 Skip package release jobs for dev tags
  .github/workflows/packages.yaml
Labels: ci

#311 Update tag pattern in GitHub Workflows
  .github/workflows/cpu-ci.yml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/lint.yaml
  .github/workflows/merlin.yml
  .github/workflows/packages.yaml
  .github/workflows/release-drafter.yaml
Labels: ci

#309 Add support for cuDF's struct dtype
  merlin/dtypes/aliases.py
  merlin/dtypes/base.py
  merlin/dtypes/mappings/cudf.py
  merlin/dtypes/registry.py
Labels: enhancement

#256 Remove warning about compound tags deprecation
  merlin/schema/tags.py
Labels: chore

#296 Make `ColumnSelector.all` a property instead of a manually set attribute
  merlin/dag/selector.py
  tests/unit/dag/test_column_selector.py
Labels: bug

#285 Add `as_tensor_type` method to `TensorTable` for framework column conversion
  merlin/table/cupy_column.py
  merlin/table/tensor_table.py
  merlin/table/tensorflow_column.py
  merlin/table/torch_column.py
  tests/unit/table/test_tensor_table.py
Labels: enhancement

#286 Add optional `schema` parameter to `from_df` method on `TensorTable`
  merlin/table/conversions.py
  merlin/table/tensor_table.py
  tests/unit/table/test_tensor_table.py
Labels: enhancement

#290 Add `actionlint` to pre-commit-config to check for valid GitHub Workflow config
  .github/actionlint.yaml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/lint.yaml
  .github/workflows/tox.yml
Labels: ci

#315 Add problem matcher for actionlint to annotate errors
  .github/actionlint-matcher.json
  .github/workflows/lint.yaml
Labels: ci

#317 Enable Compound Tag Selection and Removal to work with atomic tags and strings
  merlin/dtypes/__init__.py
  merlin/schema/schema.py
  merlin/schema/tags.py
  tests/unit/schema/test_schema.py
  tests/unit/schema/test_tags.py
Labels: enhancement

#312 Add `Rename` to the set of core DAG ops that work in all DAGs
  merlin/dag/ops/rename.py
  merlin/table/tensor_table.py
  merlin/testing/__init__.py
  merlin/testing/assert_equals.py
  tests/unit/dag/ops/test_rename.py
Labels: enhancement, api

#319 Handle schema inference in Dataset with empty list col
  merlin/core/dispatch.py
  merlin/io/dataset.py
  tests/unit/io/test_dataset.py
Labels: chore

#323 remove cupy-cuda11x from tox test environment
  requirements-gpu.txt
Labels: ci

#322 Build docs for stable branch and make default
  .github/workflows/docs-sched-rebuild.yaml
  README.md
  docs/source/conf.py
Labels: documentation

#325 Create stable branch locally in `docs-sched-rebuild` to enable stable docs build
  .github/workflows/docs-sched-rebuild.yaml
Labels: documentation

#327 Skip errors if branch tracking fails in `docs-sched-rebuild`
  .github/workflows/docs-sched-rebuild.yaml
Labels: documentation

#329 Fix example utilization script in docstrings of distributed class
  merlin/core/utils.py
Labels: documentation, chore

#331 Use compat.cupy to determine whether to run tests on GPU in test_udf
  tests/unit/dag/ops/test_udf.py
Labels: ci

#335 Fix an issue with data format detection in executors
  merlin/dag/executors.py
Labels: bug

#336 fix logic for refit and fitted attribute
  merlin/dag/executors.py
Labels: bug

#337 add npy export capability to dataset
  merlin/core/dispatch.py
  merlin/io/dataset.py
  requirements.txt
  tests/unit/io/test_dataset.py
Labels: enhancement

#328 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci

#330 Update Docs Theme to use `sphinx-book-theme`
  .gitignore
  docs/source/_static/NVIDIA-LogoBlack.svg
  docs/source/_static/NVIDIA-LogoWhite.svg
  docs/source/_static/css/custom.css
  docs/source/_static/css/versions.css
  docs/source/_static/favicon.png
  docs/source/_static/js/rtd-version-switcher.js
  docs/source/_templates/layout.html
  docs/source/_templates/merlin-ecosystem.html
  docs/source/_templates/versions.html
  docs/source/conf.py
  requirements-docs.txt
Labels: documentation
